### ISSUE TITLE
How can I test Azure ATP?

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/ATADocs#171]
"nslookup -" &gt; enter &gt; "ls -d" isn't a real sequence of commands. Please correct, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73885e78-0c05-9359-b85d-e76e12f02662
* Version Independent ID: be8e600a-3e61-ce2b-1cb7-09a40ef66533
* Content: [Azure Advanced Threat Protection frequently asked questions](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-technical-faq)
* Content Source: [ATPDocs/atp-technical-faq.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-technical-faq.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by Jc692488** [comment]
Can you fix it please

**Comment by Jc692488** [comment]
Can you please be more specific or more detail on how to fix my issues or can you what do I do

**Comment by Jc692488** [comment]
Can you please be more specific or more detail on how to fix my issues or can you what do I do

**Comment by pyoungberg** [comment]
> Can you please be more specific or more detail on how to fix my issues or can you what do I do

sorry, come again?

**Comment by mlottner** [comment]
@pyoungberg The most simple way to test Azure ATP is described in detail here: [https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-playbook-reconnaissance#run-nslookup-from-victimpc](url). The previous method of using only _nslookup_ is no longer supported due to the addition of new alerts with longer learning periods. I'll add the new method back to this page as well. Let me know if you have any issues testing using the **Security alert lab** method.
