### ISSUE TITLE
Additional info request

### ISSUE THREAD

**Issue by 1800Zeta** [MicrosoftDocs/ATADocs#220]
Under the section titled Suspicious additions to sensitive groups (external ID 2024), it mentions that you need specific auditing requirements. Please can you link to those requirements? I already have them in place but think it would be useful to link to them

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9ccfb4-ebec-0647-d1c4-20040a07edb5
* Version Independent ID: 77bb209d-7236-ee50-ab6a-868714036ac8
* Content: [Azure ATP domain dominance security alerts](https://docs.microsoft.com/en-gb/azure-advanced-threat-protection/atp-domain-dominance-alerts#suspicious-additions-to-sensitive-groups-external-id-2024)
* Content Source: [ATPDocs/atp-domain-dominance-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-domain-dominance-alerts.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@1800Zeta Thanks for taking the time to give us your feedback. Were you referring to the following sentence? "Make sure your domain controllers are auditing the events needed."  Your issue may be because we recently identified an issue where links don't show as links after being clicked once when viewing docs pages with Microsoft Edge. The text "auditing the events" needed is currently a link to the advanced audit policy check page. Or were you referring to something else you think should be a link to the auditing requirements page? Again, appreciate your contribution to our community.

**Comment by mlottner** [comment]
#please-close
