### ISSUE TITLE
log locations

### ISSUE THREAD

**Issue by bradrush** [MicrosoftDocs/ATADocs#227]
I think these log locations might be out of date as I cannot find anything in most of the suggested places despite ATP being installed and working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbd5a7f-77eb-bc4c-d696-e834ac108be0
* Version Independent ID: 164d99ad-3ecc-0031-b722-75533f8348f1
* Content: [Troubleshooting Azure Advanced Threat Protection using the logs](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/troubleshooting-atp-using-logs)
* Content Source: [ATPDocs/troubleshooting-atp-using-logs.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/troubleshooting-atp-using-logs.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@bradrush Thanks for taking the time to comment here. Default sensor and deployment log locations haven't changed. What may have happened is that when you installed the sensors, you chose to install outside the default location (perhaps on another drive). Try a full drive search to locate them.

**Comment by mlottner** [comment]
@bradrush I should have asked if you meant deployment or sensor logs. If you can't locate runtime logs, there is another possibility, which is that due to hardened permissions on the default folder or a security product you have protecting that location, it may have blocked it. 
If that is your scenario, check the permissions on the default folder.  Local system and AzureATPSensor virtual service accounts should have write permissions to this folder.

If that doesn't help, please log a support call so that our engineering team can check for write errors with your instance and help you resolve the issue.

**Comment by bradrush** [comment]
Thanks mlottner, perhaps you are right but after deploying via intune with no other customisations, no logs or folders were present in these locations.
