### ISSUE TITLE
Seeking Clearifications

### ISSUE THREAD

**Issue by shingy69** [MicrosoftDocs/ATADocs#244]
We already have Windows Defender ATP enable with our subscripion, this guide don't explain or provide links to inform admins how to or where to integrate the two products. The integration guide is provided [elsewhere](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/integrate-wd-atp). 

Obviously without this knowledge any attempts to create an Azure Advance Threat Protection instance will result in error. "Your instance was not created because a security group with same name already exists in AAD. Delete the existing security group and try again." 

So how does one download the ATP sensor for DCs for Azure ATP with the error above? Is it under MS Defender Security Center - Settings - "Select operating system to start onboarding process"? Thanks.

**Comment by mlottner** [comment]
@shingy69 Thanks for your question. 
The Windows Defender ATP and Azure ATP integration guide you linked to is already within Azure ATP documentation, so I'm unclear as to where you expect it to be relocated. 
Let us know where you expected to find it, so we can try to improve that integration experience between products. 
With regards to the installation issue:
If, when trying to create an Azure ATP instance, you are receiving this error _"Your instance was not created because a security group with same name already exists in AAD. Delete the existing security group and try again."_, it means that you previously created an instance of Azure ATP and it must be deleted before you can create another. The Azure ATP instance creation process has nothing to with your existing Windows Defender ATP subscription and one will not block the other. 

Appreciate you contributing to our community and happy to get your feedback.

**Comment by mlottner** [comment]
#please-close
