### ISSUE TITLE
About ProxyURL syntax

### ISSUE THREAD

**Issue by kk-koji** [MicrosoftDocs/ATADocs#273]
In most cases, the syntax of the ProxyURL is "HTTP:" It is possible to add the information?
ProxyUrl="https://proxy.contoso.com:8080" or ProxyUrl="http://proxy.contoso.com:8080"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7823584-21cb-81b3-7e2b-8fd521bc3ae1
* Version Independent ID: f312a146-a76c-9adb-0e36-f0f98d91051a
* Content: [Configure your proxy or firewall to enable Azure ATP communication with the sensor](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/configure-proxy#feedback)
* Content Source: [ATPDocs/configure-proxy.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/configure-proxy.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@kk-koji Thanks for taking the time to contact us. 
Will discuss with the product team and update the page as needed. 
@shsagir

**Comment by shsagir** [comment]
@kk-koji Thanks for your feedback. After investigating, we've discovered you're referring to the syntax in the table under [Configure the proxy](https://docs.microsoft.com/azure-advanced-threat-protection/configure-proxy#configure-the-proxy). This table shows sample syntax for completing the proxy setup and the sample URL is expected to be replaced with the actual URL of the proxy. Therefore, we respectfully decline to fix this. But, thanks again; we always appreciate feedback on our documentation
Because we cannot change the referenced page to include the information and functionality that you're asking for, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.
