### ISSUE TITLE
Multi Processor Group

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/ATADocs#286]
Can we confirm that if ALL the VM's are running Server 2016 then we do NOT need to be concerned about HyperThreading being enabled on the Guest OS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a56ac5-d132-1427-4c55-12921ec978c7
* Version Independent ID: aad125e7-7fa3-5fec-e025-2da79e11f44a
* Content: [Troubleshooting Azure ATP known issues](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/troubleshooting-atp-known-issues#multi-processor-group-mode)
* Content Source: [ATPDocs/troubleshooting-atp-known-issues.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/troubleshooting-atp-known-issues.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by mlottner** [comment]
@dcaddick Thanks for taking the time to ask this question on docs. 

It should work, but it might work with suboptimal performance.
We explicitly mention to turn off hyperthreading regardless of multi processor group for this reason. 
Also, if you have an HP host, you may also need the following BIOS config (due to a bug in some of HP’s BIOS versions):
https://docs.microsoft.com/advanced-threat-analytics/troubleshooting-ata-known-errors#multi-processor-group-mode

I'm closing this issue for now, but feel free to continue to comment or ask questions here as needed.

**Comment by mlottner** [comment]
#please-close
