### ISSUE TITLE
Account UPN

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/ATADocs#304]
Seems that the service account must have correct UPN filled within AD properties. The requirements should be mentioned there also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed304132-bdfe-bea6-e9f8-44f45d1651c2
* Version Independent ID: f5bdd742-716b-de60-1f73-3555c460f03c
* Content: [Connect Azure ATP to Active Directory quickstart](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/install-atp-step2)
* Content Source: [ATPDocs/install-atp-step2.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/install-atp-step2.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@Kazzan Thanks for your feedback. After investigating, we've discovered there are no specific requirements when it comes to UPN settings, the requirement is that the service account must have read access to the AD. Therefore, there is no update required for the doc.

Because we cannot change the referenced page to include the information that you're asking for, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.
