### ISSUE TITLE
Where is the link to download the tool?

### ISSUE THREAD

**Issue by marcosmcampos** [MicrosoftDocs/ATADocs#334]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29720d50-2bdb-f6a8-5be0-71bc27bef143
* Version Independent ID: 6be60338-bb13-e166-946a-067de5daa5b9
* Content: [Planning your Azure Advanced Threat Protection deployment quickstart](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-capacity-planning)
* Content Source: [ATPDocs/atp-capacity-planning.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-capacity-planning.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@marcosmcampos Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@marcosmcampos Thanks again for your feedback. After investigating, we've discovered that the link in the topic is correct and take you to the GitHub page where you can download the tool. 

Because there is no change required to the page, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.
