### ISSUE TITLE
IP address range????

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/ATADocs#411]
We see this service reaching out to a IP range of 198.143.32.0/19.  Is this as expected because the lookup of those ranges do not reference back to a Microsoft owned IP.  This is very concerning to us.  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89fcd13c-b9a0-bb56-3bcc-c9981530aaf5
* Version Independent ID: a36ab1d9-02c8-6339-6237-99679b250f75
* Content: [Azure Advanced Threat Protection Network Name Resolution](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/atp-nnr-policy)
* Content Source: [ATPDocs/atp-nnr-policy.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/atp-nnr-policy.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@SquirrelAssassin Thanks for contacting Microsoft about your issue.

As we understand it, you're describing a problem with the product itself and not with the product documentation. Please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com) so that we can investigate.
