### ISSUE TITLE
VMware virtual machine sensor issue

### ISSUE THREAD

**Issue by EricSMurphy** [MicrosoftDocs/ATADocs#446]
Hello, I have a customer who is seeking clarification on the troubleshooting steps for VMware virtual machine sensor issue. Specifically the statement that says: "Set the following to Disabled in the virtual machine's NIC configuration: IPv4 TSO Offload." The documentation doesn't clarify if this setting needs to be configured on the Host, the Guest or both. Our assumption is to configure it on the Guest OS, but it's not clear. The same goes for the LSO setting. Additionally, there are no statements of impact or reasons why these need to be disabled (especially if some organizations rely on these settings). The only statement we have is "This can happen because of a configuration mismatch in VMware" Can anyone explain more about what the mismatch in VMware is? Thanks in advance!

Summary:

1. Does the VM Nic configuration: IPv4 TSO Offload and LSO need to be set to disabled on the Host OS, Guest OS or both?
2. Are there any known impacts of disabling these settings? 
3. What is the configuration mismatch in VMware that the documentation refers to?

**Comment by shsagir** [comment]
@EricSMurphy Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@EricSMurphy Thanks for your feedback. You may find the following information from the product team useful.

1. The configuration needs to be set on the Guest OS. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow.
2. For information about known impact, we are not aware of any issues resulting from disabling this setting, but you should check with WMWare.
3. With the setting enabled, the capturing driver may not work as expected and may result in sensor packet drop (some traffic may not be analyzed), though some customers might not experience any issues at all.

If you have any further questions relating to this issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com) so that we can investigate.
