### ISSUE TITLE
Possible missing hyperlink

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/ATADocs#459]
Under "Suspected Kerberos SPN exposure..." there's a numbered item (no. 1) under "TP,B-TP, or FP" that says "in Understand the scope of the breach".  But this text is not linked to anything to continue exploring.  Also, the "in" and "Understanding" are jammed together.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db9bf93d-2f09-90ca-5feb-4106a4f8abb2
* Version Independent ID: e03df8b6-624b-30a8-2502-6be59ff98606
* Content: [Microsoft Defender for Identity compromised credentials phase security alerts](https://docs.microsoft.com/en-us/defender-for-identity/compromised-credentials-alerts#suspected-kerberos-spn-exposure-external-id-2410)
* Content Source: [ATPDocs/compromised-credentials-alerts.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/compromised-credentials-alerts.md)
* Service: **microsoft-defender-for-identity**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@Skatterbrainz Thanks for your feedback. After investigating, we've discovered there is a space between the words "in" and "Understand" and the text of "Understand the scope of the breach" refers to the heading a few lines under the step and hence does not require a link. Therefore, we do not see a need for change. But, thanks again; we always appreciate feedback on our documentation.
Because we cannot change the referenced page to include the information and functionality that you're asking for, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.
